import { ColorGrade } from "../types";

/**
 * Generates an industry-standard 3D LUT in Adobe .cube format.
 * It builds a 17x17x17 color grid and applies the exact same math
 * as our browser grading engine, exporting a fully functional LUT.
 */
export function generateCubeLUT(grade: ColorGrade, lutName: string = "Vidhan_Custom_Look"): string {
  const size = 17; // Industry standard compact 3D LUT size
  let cubeText = `# LUT generated by Vidhan Bommalla AI Look Designer\n`;
  cubeText += `# Creative Grade: ${lutName}\n`;
  cubeText += `TITLE "${lutName.replace(/[^a-zA-Z0-9_]/g, "_")}"\n`;
  cubeText += `LUT_3D_SIZE ${size}\n\n`;

  // Pre-calculate coefficients
  const expFactor = 1.0 + (grade.exposure / 100.0);
  const contrastFactor = 1.0 + (grade.contrast / 100.0);
  const satFactor = 1.0 + (grade.saturation / 100.0);
  
  // Temperature (Warm/Cool) & Tint (Green/Magenta) offsets
  // Map -100..100 to subtle color cast offsets
  const rTempOffset = (grade.temperature / 100.0) * 0.15 + (grade.tint / 100.0) * 0.05;
  const gTempOffset = -(grade.tint / 100.0) * 0.1;
  const bTempOffset = -(grade.temperature / 100.0) * 0.15 + (grade.tint / 100.0) * 0.05;

  // Lift, Gamma, Gain conversions
  // Map wheel values (-50..50) to colorist math parameters
  const liftR = grade.lift.r / 100.0; // shadow offset
  const liftG = grade.lift.g / 100.0;
  const liftB = grade.lift.b / 100.0;

  const gammaR = Math.pow(2, -grade.gamma.r / 50.0); // gamma exponent
  const gammaG = Math.pow(2, -grade.gamma.g / 50.0);
  const gammaB = Math.pow(2, -grade.gamma.b / 50.0);

  const gainR = 1.0 + (grade.gain.r / 50.0); // highlight multiplier
  const gainG = 1.0 + (grade.gain.g / 50.0);
  const gainB = 1.0 + (grade.gain.b / 50.0);

  // Rec.709 Luma Coefficients
  const lumaR = 0.2126;
  const lumaG = 0.7152;
  const lumaB = 0.0722;

  // Loop through 3D color cube (Blue outer, Green middle, Red inner loop)
  for (let bIndex = 0; bIndex < size; bIndex++) {
    const bIn = bIndex / (size - 1);
    for (let gIndex = 0; gIndex < size; gIndex++) {
      const gIn = gIndex / (size - 1);
      for (let rIndex = 0; rIndex < size; rIndex++) {
        const rIn = rIndex / (size - 1);

        // 1. Apply Lift, Gamma, Gain (LGG)
        // Lift adds offset targeting darks: (1 - input) * lift + input
        let r = rIn + (1.0 - rIn) * liftR;
        let g = gIn + (1.0 - gIn) * liftG;
        let b = bIn + (1.0 - bIn) * liftB;

        // Gamma scales midtones (power function)
        r = r > 0 ? Math.pow(r, gammaR) : 0;
        g = g > 0 ? Math.pow(g, gammaG) : 0;
        b = b > 0 ? Math.pow(b, gammaB) : 0;

        // Gain multiplies highlights
        r = r * gainR;
        g = g * gainG;
        b = b * gainB;

        // 2. Exposure & Temperature & Tint
        r = r * expFactor + rTempOffset;
        g = g * expFactor + gTempOffset;
        b = b * expFactor + bTempOffset;

        // 3. Contrast relative to midgray (0.5)
        r = (r - 0.5) * contrastFactor + 0.5;
        g = (g - 0.5) * contrastFactor + 0.5;
        b = (b - 0.5) * contrastFactor + 0.5;

        // 4. Saturation (interpolate with Luma)
        const luma = r * lumaR + g * lumaG + b * lumaB;
        r = luma + (r - luma) * satFactor;
        g = luma + (g - luma) * satFactor;
        b = luma + (b - luma) * satFactor;

        // Clamp values to [0.0, 1.0]
        const rOut = Math.max(0.0, Math.min(1.0, r));
        const gOut = Math.max(0.0, Math.min(1.0, g));
        const bOut = Math.max(0.0, Math.min(1.0, b));

        // Append line (formatted to 6 decimal places)
        cubeText += `${rOut.toFixed(6)} ${gOut.toFixed(6)} ${bOut.toFixed(6)}\n`;
      }
    }
  }

  return cubeText;
}

/**
 * Utility to trigger a local browser download for the LUT
 */
export function downloadLUT(grade: ColorGrade, lutName: string = "Vidhan_Custom_Look") {
  const cubeContent = generateCubeLUT(grade, lutName);
  const blob = new Blob([cubeContent], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  
  const link = document.createElement("a");
  link.href = url;
  link.download = `${lutName.toLowerCase().replace(/[^a-z0-9]/g, "_")}.cube`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
